from run_chat_client import *
from create_hidden_service_and_server import *
from create_onion_page import *
from generate_qr import *
from crypto import *

path = os.path.dirname(os.path.realpath(__file__)) + "/"
tor_path_file_path = path + "files/others/tor_path_file.txt"

main_menu = "\nMAIN MENU" \
            "\n0. Configure with Tor" \
            "\n1. Create new hidden service and chat server" \
            "\n2. Generate encryption keys for chat" \
            "\n3. Run chat client" \
            "\n4. Create onion webpage" \
            "\n5. Generate QR codes for chat server" \
            "\n6. Generate QR codes for onion page" \
            "\n7. Generate QR codes for your encryption keys" \
            "\n8. Exit"

if __name__ == '__main__':
    print("Welcome to Onymochat"
          "\nEmpowering journalists and whistleblowers"
          "\nBuilt by: Samrat Dutta"
          "\nMy Github: https://www.github.com/samratduttaofficial"
          "\nWant to hire me? https://www.linkedin.com/in/samratduttaofficial"
          "\nLoved the project? Please buy me a coffee. https://www.buymeacoffee.com/SamratDutta")

    while True:
        print(main_menu)
        choice = input("Enter your choice: ")
        if choice == "0":
            try:
                print("Enter the path to tor.exe in the TorBrowser folder."
                      "\nExample (For Windows): C:\\user\\Desktop\\Tor Browser\\Browser\\TorBrowser\\Tor\\tor.exe"
                      "\nExample (For Mac): Applications\\TorBrowser.app\\Tor\\tor.real"
                      "\nLinux users just write 'tor' without the quotations.\n")
                tor_path = str(input("Enter the path: "))
                tor_path_file = open(tor_path_file_path, "w")
                tor_path_file.write(tor_path)
                print("Done!"
                      "\nClose and restart the program for the changes to take effect.")
            except FileNotFoundError:
                print("tor_path_file.txt is not found. Go to " + path + "/files/others and make a file named "
                                                                        "tor_path_file.txt.")
            except:
                print("Some error occurred. Please try with a proper path.")
        elif choice == "1":
            try:
                create_hidden_service_and_server()
            except Exception as e:
                if "Program Closed" in str(e):
                    continue
                else:
                    print(e)
                    print("Some error occurred!")
        elif choice == "2":
            try:
                public_key, private_key = crypto.import_keys(print_existing_keys=True)
            except:
                try:
                    public_key, private_key = crypto.generate_keys()
                except Exception as e:
                    if "Error in generate_keys" in str(e):
                        print("An error occurred. "
                              "Make sure you have entered a correct private key generated by Onymochat.")
        elif choice == "3":
            try:
                run_chat_client()
            except Exception as e:
                if "Program Closed" in str(e):
                    continue
                else:
                    print(e)
                    print("Some error occurred!")
        elif choice == "4":
            try:
                create_onion_page()
            except Exception as e:
                if "Program Closed" in str(e):
                    continue
                else:
                    print(e)
                    print("Some error occurred!")
        elif choice == "5":
            generate_hidden_service_qr()
        elif choice == "6":
            generate_onion_page_qr()
        elif choice == "7":
            generate_encryption_keys_qr()
        elif choice == "8":
            break
        else:
            print("Please enter a valid choice.")
